//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkBlogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int ID { get; set; }
        public int IDPost { get; set; }
        public int IDUsuario { get; set; }
        public string Texto { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
